version: '3'

services:
  database:
    image: postgres:14.2
    ports:
      - "3306:5432"
    volumes:
      - ./volumes/postgres/:/var/lib.postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=tiny_link
      - POSTGRES_PORT=3036
    networks:
      - net
  tinylink_dev:
    image: tinylink/latest
    ports:
      - "8080:8080"
    networks:
      - net
